upgrade to Kotlin 1.5 to fix AS 2022.3.1
In Android Studio 2022.3.1 it seems Kotlin 1.4 is no longer supported
the following error is shown when attempting to build:
java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.kotlin.com.intellij.pom.java.LanguageLevel