New implementation FirebaseMessaging.getToken
* New getTokenWithClassFirebaseMessaging method that uses the newer
FirebaseMessaging.getToken() API added in firebase-messaging:21.0.0.
* Since all apps may not have updated to firebase-messaging:21.0.0 or
newer we are catching NoClassDefFoundError & NoSuchMethodError
and falling back to FirebaseInstanceId.getToken